# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import interface_wrap
else:
    import interface_wrap

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class action(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    rot = property(interface_wrap.action_rot_get, interface_wrap.action_rot_set)
    move = property(interface_wrap.action_move_get, interface_wrap.action_move_set)

    def __init__(self):
        interface_wrap.action_swiginit(self, interface_wrap.new_action())
    __swig_destroy__ = interface_wrap.delete_action

# Register action in interface_wrap:
interface_wrap.action_swigregister(action)

class Tetris(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    r = property(interface_wrap.Tetris_r_get, interface_wrap.Tetris_r_set)
    c = property(interface_wrap.Tetris_c_get, interface_wrap.Tetris_c_set)

    def __init__(self, R, C, FR):
        interface_wrap.Tetris_swiginit(self, interface_wrap.new_Tetris(R, C, FR))

    def get_state(self, a):
        return interface_wrap.Tetris_get_state(self, a)
    __swig_destroy__ = interface_wrap.delete_Tetris

# Register Tetris in interface_wrap:
interface_wrap.Tetris_swigregister(Tetris)



